### ISSUE TITLE
transR.cpp:427:59: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]

### ISSUE THREAD

**Issue by dengyang17** [thunlp/TensorFlow-TransX#1]
When I was using the transX.cpp, I got this warning. How could I fix this.

**Comment by THUCSTHanxu13** [comment]
The warning will not affect the results. If you want to fix the warning, you can change "426:for (int a = 0; a < transRThreads; a++)" to "for (long a = 0; a < transRThreads; a++)". I will fix the codes as soon as possible.

**Comment by dengyang17** [comment]
Thanks. Although the warning has been fixed, after runing the code, nothing came out, neither error nor result.

**Comment by THUCSTHanxu13** [comment]
string inPath = "./data/"; and string outPath = "./out/"; define the input  and output path. If there is not a folder called "out" in the current directory, the results can not be written into the output files. You need "mkdir out" or change outPath to "" before you run the code.

**Comment by dengyang17** [comment]
I mean after the whole epoch [train_transe(NULL);] , it doesn't save the model [out_transe();]. And I have set the path.

**Comment by hfsugar** [comment]
Where is the output file? I didn't find " string outPath = "./out/" " in your code. How to get the vectors of entities and relations. Thank you!

**Comment by THUCSTHanxu13** [comment]
To use the TensorFlow-TransX, "saver.save(sess, 'model.vec')" will output the vectors to the file "model.vec" without any other operations. To use the C version Fast-TransX, the default output files will be "./out/relation2vec.vec" and "./out/entity2vec.vec". If there is not a folder called "out", "fopen" can not create "./out/relation2vec.vec" and "./out/entity2vec.vec". Note that, "fopen" in C can only create files. Changing outPath in TransR.cpp to "./" will let you get the vectors.
