### ISSUE TITLE
How to explain the relation in triple?

### ISSUE THREAD

**Issue by zhongkaiwang** [thunlp/TensorFlow-TransX#10]
One relation has three parts in a general way.  Do you consider the meaning of every part when building Knowledge Graph?  For example, in the relation, "/tv/tv_program/languages", what is the relationship between two entities and  three parts divided by slash. Two entities are the O.C. and English. Thanks!

**Comment by THUCSTHanxu13** [comment]
For nodes of freebase, they are defined as /domain/type/object. For edges of freebase, they are defined as /domain/type/link. For "/tv/tv_program/languages", tv is its domain, tv_program is its type, and languages is its property. If you want to knowledge more about freebase, you can find information on https://developers.google.com/freebase/

**Comment by zhongkaiwang** [comment]
Thanks, I get it. Did you use the first two parts, domain and type, in your experiment? In other words, do you consider using them to do something in the future?

**Comment by THUCSTHanxu13** [comment]
Domain and types are not used in these models. To the best of my knowledge, there are some methods using domain and types. However, I don’t remember what they are. I think you can find papers you want by google scholar.

**Comment by zhongkaiwang** [comment]
OK, thank you for your answer.
