### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by icaro56** [thunlp/TensorFlow-TransX#13]
Please, could you put the code for test?

Thank you.

**Comment by icaro56** [comment]
I was able to restore the trained model with this code:

import tensorflow as tf
with tf.Graph().as_default():
    with tf.Session() as sess:
        new_saver = tf.train.import_meta_graph('out/transr/model.vec.meta')
        new_saver.restore(sess, 'out/transr/model.vec')
        graph = tf.get_default_graph()

        print("Model restored.")
        print("ent_embedding : %s" % graph.get_tensor_by_name('model/ent_embedding:0'))

Please, how do I test now?

**Comment by THUCSTHanxu13** [comment]
I have pushed codes for model testing.

**Comment by icaro56** [comment]
Thank you
