### ISSUE TITLE
 Questions about test.txt, valid.txt and type_constrain.txt

### ISSUE THREAD

**Issue by icaro56** [thunlp/TensorFlow-TransX#14]
Are the relationships present within the test.txt and valid.txt files existing relations or relations that are not true? How do I create these files to my dataset?

Could you explain the new file type_constrain.txt?

Thanks.

**Comment by THUCSTHanxu13** [comment]
1. train.txt, valid.txt and test.txt are the main components of the datasets. 

2. You can run n-n.py to generate type_constrain.txt, 1-1.txt, 1-n.txt, n-1.txt, n-n.txt, test_all.txt. 

3. Besides overall link prediction results, these models categorize the relationships according to the cardinalities of their head and tail arguments into four classes: 1-TO-1, 1-TO-MANY, MANY-TO-1, MANY-TO-MANY. Our testing codes can also evaluate these detailed results by category of relationship. n-n.py will split test.txt into four parts (1-1,1-n,n-1,n-n) and label all triples in test.txt.

4. type_constrain.txt is used for type-constrained link prediction (http://www.dbs.informatik.uni-muenchen.de/~krompass/papers/TypeConstrainedRepresentationLearningInKnowledgeGraphs.pdf).

**Comment by icaro56** [comment]
So, are the valid.txt and test.txt correct/positive triples?

**Comment by THUCSTHanxu13** [comment]
valid.txt and test.txt are positive triples.

**Comment by icaro56** [comment]
Thank you
