### ISSUE TITLE
I didn't find " string outPath = "./out/" " . Where is the output file?

### ISSUE THREAD

**Issue by hfsugar** [thunlp/TensorFlow-TransX#2]
Where is the output file? I didn't find " string outPath = "./out/" " in your code. How to get the vectors of entities and relations. Thank you!

**Comment by THUCSTHanxu13** [comment]
If you use the TensorFlow-TransX, "saver.save(sess, 'model.vec')" will output the vectors to the file "model.vec".  ''' string outPath = "./out/"  ''' is used in the another project Fast-TransX.

**Comment by hfsugar** [comment]
Thank you for your responding. I tried both TensorFlow-TransX and Fast-TransX. In TensorFlow-TransX, the mode.vec is in messy code. In Fast-TransX, I mkdir 'out' but it doesn't work, There is no output in the folder out.

**Comment by THUCSTHanxu13** [comment]
Please send your code to me (cst_hanxu13@163.com), I will debug for you.

**Comment by THUCSTHanxu13** [comment]
To get the information in the model.vec, you need use "tf.train.Saver().restore()", you get the concrete information from "https://www.tensorflow.org/api_docs/python/tf/train/Saver".
