### ISSUE TITLE
InvalidArgumentError when running transR.py in test mode

### ISSUE THREAD

**Issue by swathi-ssunder** [thunlp/TensorFlow-TransX#20]
InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'model/read_inputs/Placeholder_5' with dtype int32 and shape [?]

I figured that this is because `predict` is being computed in the test step and `predict` depends on `matrix` which needs `neg_r`.

My solution to overcome this problem was to create 2 different projection matrices, like 

```
pos_matrix = tf.reshape(tf.nn.embedding_lookup(self.rel_matrix, self.pos_r), [-1, sizeR, sizeE])
neg_matrix = tf.reshape(tf.nn.embedding_lookup(self.rel_matrix, self.neg_r), [-1, sizeR, sizeE])
```
and using these accordingly in the subsequent computations.

Is this the right way?

**Comment by THUCSTHanxu13** [comment]
Thank you for your suggestion! Your method is right and I have fixed this bug.
