### ISSUE TITLE
Input Files path:

### ISSUE THREAD

**Issue by liutianling** [thunlp/TensorFlow-TransX#23]
I run the transE directly
And then I got this error:
Input Files path:
Input Files path:
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

The data path is already in the config.I don't konw why coming this error?
Thank you!

**Comment by acadTags** [comment]
same issue here

**Comment by THUCSTHanxu13** [comment]
Is your python version 3.6?

**Comment by acadTags** [comment]
Yes.

**Comment by liutianling** [comment]
@THUCSTHanxu13 请问下训练数据的问题，这是我从FB15K中摘出来的一条数据
/m/07pd_j       /m/02l7c8       /film/film/genre
为什么训练数据不是　head  tail relation 的形式，比如　马云　执掌　阿里巴巴
训练数据的为什么是多个关系　film/film/genre　这种形式，半路开始做这方面的东西，不是很理解，希望能帮忙解释一下
另外WN18中的数据形式就是这样的　02174461        02176268        _hypernym
感觉这种三元组的形式很清晰，请问为什么会有这两种不同的数据形式？
谢谢。

**Comment by THUCSTHanxu13** [comment]
(h, r, t) 和 (h, t, r)并没有本质区别，FB15K的原始数据就是h, t, r的形式。另外wn是来源于wordnet，fb15K来源于freebase，数据里面的编号和关系都是这些公开知识图谱定义好的，更多信息你可以访问这些公开知识图谱的网站

**Comment by liutianling** [comment]
@THUCSTHanxu13 谢谢你的回复。我的意思不是说(h, r, t)或者(h, t, r)，我的意思是说FB15K数据集中的数据
/m/07pd_j /m/02l7c8 /film/film/genre
他的关系为什么不直接是genre， 而是 /film/film/genre这种形式，我不知道这种形式是什么意思，每个 / 后面代表的什么意思？
另外，你说的那些网站方便说一下吗，我不太了解，谢谢。

**Comment by BrambleXu** [comment]
@acadTags @liutianling Did you guys solve the problem? I also get the file path error with python 3.6.

**Comment by midneet** [comment]
same error still, seems they didn't support python3 here, what a pity. (python2 works for the path issue)

**Comment by rrrimp** [comment]
> 

@柳天岭 我也有这样的疑问，请问你搞明白了吗

**Comment by rrrimp** [comment]
@[liutianling](https://github.com/liutianling) 我也有这样的疑问，请问你搞明白了吗

**Comment by YingXu-swim** [comment]
@liutianling 我也有这样的疑问，请问你搞明白了吗
