### ISSUE TITLE
the evalute result, could you explain it?

### ISSUE THREAD

**Issue by hljjjmssyh** [thunlp/TensorFlow-TransX#26]
I have run the transR.py file for 1000 epoch. But I can't get the  same result as the original paper, especially meanbank.
![image](https://user-images.githubusercontent.com/24326757/50061677-80187f00-01dd-11e9-9c4e-46ca5de55fc4.png)

**Comment by THUCSTHanxu13** [comment]
Because the TransR must be trained with the embeddings pretrained by transE, and the diagonal matrix as initial parameters. If you randomly initialize your parameters, you may have poor results, because it is hard to converge. This detail can be found in the original implementation of TransR.
