### ISSUE TITLE
What's the difference between "results(type constraints)" and "results" in evaluation?

### ISSUE THREAD

**Issue by IdelCoder** [thunlp/TensorFlow-TransX#28]

**Comment by THUCSTHanxu13** [comment]
The "results" denote the results following the test settings in the original papers.

The "results (type constraints)" is the results of type-constrained link prediction following the settings in (http://www.dbs.informatik.uni-muenchen.de/~krompass/papers/TypeConstrainedRepresentationLearningInKnowledgeGraphs.pdf).
