### ISSUE TITLE
Code for Test

### ISSUE THREAD

**Issue by dtjayaaa12345** [thunlp/TensorFlow-TransX#4]
Hi, thanks for your helpful training code! Could you please release the code of complete testing?

**Comment by THUCSTHanxu13** [comment]
The origin version KB2E(https://github.com/thunlp/KB2E) has the testing codes. You can adopt the codes for your test.

**Comment by icaro56** [comment]
Hi, please help me. The project genenerate the model.vec files. How do I test now?
