### ISSUE TITLE
为什么train.py在训练模型时res=0？

### ISSUE THREAD

**Issue by 7231** [thunlp/TensorFlow-TransX#43]
我在运行transE.py时，设置self.testFlag = False，self.loadFromData = False，运行结果打印出来所有的res都为0。为了找到res=0的原因，我尝试打印出config.batch_size和lib.getTripleTotal() ，发现config.batch_size和lib.getTripleTotal() 也都等于0。我在init.cpp文件中找到了getTripleTotal()，按道理来说，如果fscanf(fin, "%d", &trainList[tripleTotal].h) == 1，TripleTotal就应该不为0，这与实际运行的结果不符合，请问这是怎么回事呢？

**Comment by wantolose** [comment]
出现了同样的问题，python=3.6，tensorflow=1.14，方便大家复现。

**Comment by Condor-G** [comment]
init.cpp中，setInPath函数，生成的inPath有问题，因为传递的char *path会多一些空格。这个情况不知道和Python版本有没有关系。

**Comment by THUCSTHanxu13** [comment]
这个应该是文件路径出现了问题，因为不同python版本给C代码传字符串会有一些差别，可以在C代码里面添加路径输出，然后重新编译下看看是不是文件路径的问题。
