### ISSUE TITLE
OSError: exception: access violation writing 0x0000024BFF054AB0

### ISSUE THREAD

**Issue by daidaidongdong** [thunlp/TensorFlow-TransX#44]
My environment is Windows10 and python3.7, what is your environment? When running transX.py, I got this error and I have tried many methods to no avail. Do you have any suggestion?

**Comment by THUCSTHanxu13** [comment]
Our underlying code is based on C++ and the pthread library. The pthread library can work on Liunx and OS X, yet cannot work on Windows.
