### ISSUE TITLE
How to train transx models from ipython

### ISSUE THREAD

**Issue by isspek** [thunlp/TensorFlow-TransX#7]
I want to use transx models in ipython but dont understand how training data is given as input and call main function.

I call the followings. But kernel is killed first calling then restart and main function seems not progressing.

```
import transR
transR.main()
```

**Comment by THUCSTHanxu13** [comment]
Sorry for the delay getting back to you. Maybe you can try "import transR ... transR.main(None)". I have tried the codes in my computer.
